### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by soringpenguin** [manumaticx/Ti.DrawerLayout#44]
I can't figure out how to get past this error.
I'm using SDK 3.5.1.GA

I'm pretty sure I have the module installed correctly cause it doesn't fail from the require(). I think it has to be some specific little thing I'm missing or have incorrect. Any help would be great.

Thank you

This is the log
```
[WARN] :   TiVerify: (Timer-0) [5404,5404] Verifying module licenses...
[WARN] :   dalvikvm: Unable to resolve superclass of Lcom/tripvi/drawerlayout/Drawer$1; (821)
[WARN] :   dalvikvm: Link of class 'Lcom/tripvi/drawerlayout/Drawer$1;' failed
[WARN] :   dalvikvm: Unable to resolve superclass of Lcom/tripvi/drawerlayout/Drawer$1; (821)
[WARN] :   dalvikvm: Link of class 'Lcom/tripvi/drawerlayout/Drawer$1;' failed
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Landroid/support/v7/app/ActionBarDrawerToggle;)
[WARN] :   dalvikvm: Unable to resolve superclass of Lcom/tripvi/drawerlayout/Drawer$1; (821)
[ERROR] :  dalvikvm: Could not find class 'com.tripvi.drawerlayout.Drawer$1', referenced from method com.tripvi.drawerlayout.Drawer.initDrawerToggle
[WARN] :   dalvikvm: Link of class 'Lcom/tripvi/drawerlayout/Drawer$1;' failed
[WARN] :   dalvikvm: VFY: unable to resolve new-instance 4667 (Lcom/tripvi/drawerlayout/Drawer$1;) in Lcom/tripvi/drawerlayout/Drawer;
[INFO] :   dalvikvm: Could not find method android.support.v7.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled, referenced from method com.tripvi.drawerlayout.Drawer.propertyChanged
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 5950: Landroid/support/v7/app/ActionBarDrawerToggle;.setDrawerIndicatorEnabled (Z)V
[WARN] :   dalvikvm: Unable to resolve superclass of Lcom/tripvi/drawerlayout/Drawer$1; (821)
[WARN] :   dalvikvm: Link of class 'Lcom/tripvi/drawerlayout/Drawer$1;' failed
[INFO] :   TiVerify: (Timer-0) [245,5649] Succesfully verified module licenses
[INFO] :   PersonaManager: getPersonaService() name persona_policy
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4171dda0)
[ERROR] :  TiApplication: (main) [1097,6746] Sending event: exception on thread: main msg:java.lang.NoClassDefFoundError: com.tripvi.drawerlayout.Drawer$1; Titanium 3.5.1,2015/03/05 10:08,96875c9
[ERROR] :  TiApplication: java.lang.NoClassDefFoundError: com.tripvi.drawerlayout.Drawer$1
[ERROR] :  TiApplication: 	at com.tripvi.drawerlayout.Drawer.initDrawerToggle(Drawer.java:218)
[ERROR] :  TiApplication: 	at com.tripvi.drawerlayout.Drawer.initLeftDrawer(Drawer.java:311)
[ERROR] :  TiApplication: 	at com.tripvi.drawerlayout.Drawer.processProperties(Drawer.java:392)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1209)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:500)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:507)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:491)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:469)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:670)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:564)
[ERROR] :  TiApplication: 	at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:232)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:32)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:451)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:533)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  TiApplication: 	at android.app.Activity.performCreate(Activity.java:5451)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.access$900(ActivityThread.java:169)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:146)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5487)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)
[INFO] :   Process: Sending signal. PID: 7565 SIG: 9
-- End application log -------------------------------------------------------
```
index.xml
```
<Alloy>
    <Window id="mainWindow">
        <Drawer id="drawer" module="com.tripvi.drawerlayout" />
    </Window>
</Alloy>
```
index.js
```
if (OS_ANDROID) {
    var menuTable = Alloy.createController('menu').getView();
    var contentView = Alloy.createController('main').getView();
    
    $.drawer.setLeftView(menuTable);
    $.drawer.setCenterView(contentView);

    $.mainWindow.open();
}
```
tiapp.xml
```
<modules>
        <module platform="android">com.tripvi.drawerlayout</module>
        <module platform="android">ti.map</module>
</modules>
```

**Comment by soringpenguin** [comment]
Well I feel like a fool. I finally resort to asking and I immediately get it working. I switch to SDK 4.1.0.GA and then it worked just fine.

**Comment by manumaticx** [comment]
I think we should set the minimum SDK to 4.0.0.GA - I'll test with 3.5.1.GA asap. Thanks for the pointer

**Comment by SudoPlz** [comment]
I confirm that after using the 3.5.1 backport my app started working. Thats great because I wish to support devices before Android Lollipop 5 (Api 21) and using Titanium sdk 4.0.0 and greater stops me from doing so.
