### ISSUE TITLE
java.lang.IllegalStateException in android.support.v4.app.FragmentManagerImpl.checkStateLoss

### ISSUE THREAD

**Issue by deckameron** [manumaticx/Ti.DrawerLayout#52]
Hi @manumaticx,

I have been getting this error a lot on Google Play reports and I don't know how to solve it. Could you please help me?

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1377)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:616)
	at com.tripvi.drawerlayout.Drawer.replaceCenterView(Drawer.java:413)
	at com.tripvi.drawerlayout.Drawer.processProperties(Drawer.java:483)
	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1209)
	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:502)
	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:493)
	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:471)
	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:672)
	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:232)
	at org.appcelerator.titanium.proxy.TiWindowProxy.handleMessage(TiWindowProxy.java:102)
	at ti.modules.titanium.ui.WindowProxy.handleMessage(WindowProxy.java:428)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5272)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by manumaticx** [comment]
Are you using an older version of the module?

**Comment by deckameron** [comment]
Hi @manumaticx ,
I am using 1.3.4.

**Comment by manumaticx** [comment]
Hm, it should work then. 1.3.4. does not use fragments anymore. Any chance of reproducing this?

**Comment by deckameron** [comment]
My mistake @manumaticx . I was not using 1.3.4 but 1.3.1.
I will updated it to 1.3.5.

**Comment by manumaticx** [comment]
Well, this should solve it :)
Am 22.10.2015 8:10 nachm. schrieb "Douglas Alves" <notifications@github.com

**Comment by deckameron** [comment]
It always worked so well that I've never even bothered updating it. :-)

**Comment by manumaticx** [comment]
That update was necessary to support map view
