### ISSUE TITLE
5.1.0 GA Problem

### ISSUE THREAD

**Issue by centogram** [manumaticx/Ti.DrawerLayout#53]
With the latest 5.1.0.GA sdk in android 
org.appcelerator.titanium.TiActivity cannot be cast to android.support.v7.app.ActionBarActivity .  Any ideas how to resolve this?
 
-> https://github.com/Tripvi/Ti.DrawerLayout/issues/52

**Comment by Brian-McBride** [comment]
What is the exact error?

**Comment by centogram** [comment]
```
11-23 03:27:37.594: E/AndroidRuntime(7515): java.lang.ClassCastException: org.appcelerator.titanium.TiActivity cannot be cast to android.support.v7.app.ActionBarActivity
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at com.tripvi.drawerlayout.Drawer.<init>(Drawer.java:78)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at com.tripvi.drawerlayout.DrawerProxy.createView(DrawerProxy.java:38)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:488)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:675)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:235)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at android.os.Looper.loop(Looper.java:136)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at java.lang.reflect.Method.invoke(Method.java:515)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
11-23 03:27:37.594: E/AndroidRuntime(7515): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by manumaticx** [comment]
Hi, this was actually already resolved here: https://github.com/manumaticx/Ti.DrawerLayout/commit/812ca7d8fdacc91261eb5ed39ba912a4b677bbce
but not yet released.
I'll publish a new version later today.

**Comment by centogram** [comment]
Great.   Thank you.



—

**Comment by MahmoudElmoghazy** [comment]
@manumaticx Have u make the module ?

**Comment by manumaticx** [comment]
I've just pushed the new package but I didn't have the time to test it against 5.1.0.GA - sorry!
Please let me know if this works for you

**Comment by MahmoudElmoghazy** [comment]
ok could you push the module to test it cause i have a problem in my ndk i can't make a module :)

**Comment by manumaticx** [comment]
It's here: https://github.com/manumaticx/Ti.DrawerLayout/blob/master/dist/com.tripvi.drawerlayout-android-1.3.6.zip

**Comment by MahmoudElmoghazy** [comment]
It works fine but humburger menu doesn't work :(

**Comment by manumaticx** [comment]
I'll test asap

**Comment by MahmoudElmoghazy** [comment]
thank for help :)

**Comment by Arood** [comment]
The update works but it forces the ActionBar to appear even though I've hidden it. My custom theme looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <style name="Theme.NoActionBar" parent="@style/Theme.AppCompat">
    <item name="windowActionBar">false</item>
    <item name="windowNoTitle">true</item>
    <item name="android:statusBarColor">#a00707</item>
  </style>
</resources>
```

**Comment by manumaticx** [comment]
@Arood Can you try creating the Drawer with `hideToolbar: true`?

**Comment by Arood** [comment]
@manumaticx that worked, thanks!

**Comment by MahmoudElmoghazy** [comment]
@manumaticx have u test the menu button ?!

**Comment by manumaticx** [comment]
@MahmoudElmoghazy I've just tested the [demo app](https://github.com/manumaticx/Ti.DrawerLayout-Demo-Alloy-App) with Titanium 5.1.1.GA and 1.3.6 - it works fine for me. 

What's the exact problem you are facing?

**Comment by MahmoudElmoghazy** [comment]
The heuberger menu doesn't work

**Comment by collinprice** [comment]
Thank you!
