### ISSUE TITLE
ClassCastException with 5.1.1GA SDK

### ISSUE THREAD

**Issue by asleson** [manumaticx/Ti.DrawerLayout#57]
Hello @manumaticx !

I just upgraded from Titanium SDK 5.0.0GA to 5.1.1GA to overcome a major (for me) bug in the 5.0.0GA SDK.

However, when I run my app that uses the DrawerLayout v1.3.5 module, the app fails with this stack trace snippet:

```
[ERROR] :  AndroidRuntime: Caused by: java.lang.ClassCastException: org.appcelerator.titanium.TiActivity cannot be cast to android.support.v7.app.ActionBarActivity
[ERROR] :  AndroidRuntime: 	at com.tripvi.drawerlayout.Drawer.<init>(Drawer.java:74)
[ERROR] :  AndroidRuntime: 	at com.tripvi.drawerlayout.DrawerProxy.createView(DrawerProxy.java:38)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:488)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:512)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:675)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:569)
```
Something definitely changed in the 5.1.1GA SDK, as the error goes away when I revert back to the 5.0.0GA SDK.

Could you please investigate?

Thank you very much!!!!

**Comment by asleson** [comment]
Oops, never mind.  Sorry.  I didn't see that there was a 1.3.6 version available in the dist folder.  I was looking under the "releases" tab on GitHub.  I see the commit comment for Drawer.java that changes the casting.  

Thank you so much for providing this module!!!
