### ISSUE TITLE
Fatal exception on SDK 7.0.1.GA

### ISSUE THREAD

**Issue by skoften** [manumaticx/Ti.DrawerLayout#88]
It doesn't happen every time, but I often get a fatal exception after starting up the app, and setting the left, center and right window. App crashes instantly.

Error:

```
12-27 09:48:26.149 27337 27337 E AndroidRuntime: FATAL EXCEPTION: main
12-27 09:48:26.149 27337 27337 E AndroidRuntime: Process: skoften.android.app, PID: 27337
12-27 09:48:26.149 27337 27337 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View org.appcelerator.titanium.view.TiUIView.getOuterView()' on a 
null object reference
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at com.tripvi.drawerlayout.Drawer.propertyChanged(Drawer.java:531)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at org.appcelerator.kroll.KrollPropertyChange.fireEvent(KrollPropertyChange.java:21)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1111)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:363)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at com.tripvi.drawerlayout.DrawerProxy.handleMessage(DrawerProxy.java:74)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6776)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
12-27 09:48:26.149 27337 27337 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by drauggres** [comment]
Hi. What do you set to left view?

**Comment by skoften** [comment]
Hi,

A view with a tableView. It's the main menu:

```
var leftView = Alloy.createController('menu/menuWindow').getView();

```

menuWindow.xml

```
<Alloy>	
	
	<!-- window -->
	<View id="menuWindow">
		
		<!-- menu view -->
		<View id="menuView">
			
			<!-- table -->
			<TableView id="menuTable" onClick="onRowClick">
				<RefreshControl id="refreshControl"  onRefreshstart="refreshMenu" />
			</TableView>
			
		</View>
		
	</View>

</Alloy>
```

I add the view after the drawer window has opened. But that shouldn't make a difference right?

**Comment by drauggres** [comment]
> I add the view after the drawer window has opened. But that shouldn't make a difference right?

Right.

Please try this build:
https://github.com/drauggres/Ti.DrawerLayout/releases/download/3.0.1-bug%2F88/com.tripvi.drawerlayout-android-3.0.1.zip
This is not a fix, just for understanding where the bug is. App will not crash at this point, instead it will put errors in log. Please look for "left view is null" and paste lines after it here.

**Comment by drauggres** [comment]
I think, bug is in 7.0.0 SDK ([here](https://github.com/appcelerator/titanium_mobile/commit/58ffbd5147faa90259d805957ab8957c7a84b912#diff-bec22e2efdd8b352a7754ea42f435dc7R487)). If so, you will see `activity is destroyed` in log right after `left view is null`.

**Comment by drauggres** [comment]
@skoften Try [3.0.1](https://github.com/manumaticx/Ti.DrawerLayout/releases/tag/3.0.1). Should be fixed.

**Comment by skoften** [comment]
Thanks, works!
